version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - btc_net
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    networks:
      - btc_net
  btc_node:
    image: bitcoindevelopernetwork/bitcoind-regtest
    ports:
      - 18444:18444
      - 127.0.0.1:18332:18332
      - 127.0.0.1:29000:29000
    volumes:
      - ./volumes/bitcoin/data:/bitcoin
      - ./volumes/bitcoin/config:/bitcoin/.bitcoin
    networks:
      - btc_net
  web:
    container_name: web
    image: node:18.15.0-slim
    command: sh -c "yarn install && yarn run dev"
    # build:
    #   context: .
    #   dockerfile: ./apps/web/Dockerfile
    working_dir: /usr/src/app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - btc_node
      - rabbitmq
      - api
    volumes:
      - ./apps/web:/usr/src/app
    networks:
      - btc_net
  api:
    container_name: api
    image: node:18.15.0-slim
    command: sh -c "yarn install && yarn run dev"
    restart: always
    ports:
      - 3001:3001
    working_dir: /usr/src/app
    environment:
      RABBITMQ_HOST: amqp://rabbitmq:5672
      MONGODB_CONNECTION_STRING: mongodb://Umango:tWBcLtJfwOPzFbIO@mongo-1b83556ce326.victhorious.com:27017/user-service?retryWrites=true&w=majority
    depends_on:
      - btc_node
      - rabbitmq
    volumes:
      - ./apps/api:/usr/src/app
    networks:
      - btc_net
  sse:
    container_name: sse
    image: node:18.15.0-slim
    command: sh -c "yarn install && yarn run dev"
    restart: always
    ports:
      - 3002:3001
    working_dir: /usr/src/app
    environment:
      RABBITMQ_HOST: amqp://rabbitmq:5672
      MONGODB_CONNECTION_STRING: mongodb://Umango:tWBcLtJfwOPzFbIO@mongo-1b83556ce326.victhorious.com:27017/user-service?retryWrites=true&w=majority
    depends_on:
      - btc_node
      - rabbitmq
    volumes:
      - ./apps/sse:/usr/src/app
    networks:
      - btc_net
  btc_subscriber:
    restart: always
    build:
      context: .
      dockerfile: ./apps/btc-subscriber/Dockerfile.dev
    command: sh -c "yarn install && yarn run dev"
    working_dir: /usr/src/app
    environment:
      RABBITMQ_HOST: amqp://rabbitmq:5672
      MONGODB_CONNECTION_STRING: mongodb://Umango:tWBcLtJfwOPzFbIO@mongo-1b83556ce326.victhorious.com:27017/user-service?retryWrites=true&w=majority
      UMANGO_KAFKA_BROKERS: kafka:9092
    depends_on:
      - btc_node
      - rabbitmq
    volumes:
      - ./apps/btc-subscriber:/usr/src/app
    networks:
      - btc_net
  notification_worker:
    restart: always
    image: node:18.15.0-slim
    command: sh -c "yarn install && yarn run dev"
    working_dir: /usr/src/app
    environment:
      RABBITMQ_HOST: amqp://rabbitmq:5672
    depends_on:
      - btc_node
      - rabbitmq
    volumes:
      - ./apps/notification-worker:/usr/src/app
    networks:
      - btc_net
  nginx:
    image: nginx
    ports:
      - "3333:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - btc_net
    depends_on:
      - api
      - sse

networks:
  btc_net:
    driver: bridge
